const data = [
  {
    id: 'category_1',
    title: 'Category 1',
    data: [
      {
        description: 'Lady with a Teddy',
        'image-url':
          'https://images.pexels.com/photos/3348748/pexels-photo-3348748.jpeg',
      },
      {
        description: 'Girl with camera',
        'image-url':
          'https://images.pexels.com/photos/3812944/pexels-photo-3812944.jpeg',
      },
      {
        description: 'Beautiful Girl with Glasses',
        'image-url':
          'https://images.pexels.com/photos/2100063/pexels-photo-2100063.jpeg',
      },
      {
        description: 'Redhead with frackles',
        'image-url':
          'https://images.pexels.com/photos/3228213/pexels-photo-3228213.jpeg',
      },
      {
        description: 'Girl in black dress',
        'image-url':
          'https://images.pexels.com/photos/1385472/pexels-photo-1385472.jpeg',
      },
      {
        description: 'Girl Sitting on Chair',
        'image-url':
          'https://images.pexels.com/photos/4725133/pexels-photo-4725133.jpeg',
      },
    ],
  },
  {
    id: 'category_2',
    title: 'Category 2',
    data: [
      {
        albumId: 1,
        id: 1,
        title: 'accusamus beatae ad facilis cum similique qui sunt',
        url: 'https://via.placeholder.com/600/92c952',
        thumbnailUrl: 'https://via.placeholder.com/150/92c952',
      },
      {
        albumId: 1,
        id: 2,
        title: 'reprehenderit est deserunt velit ipsam',
        url: 'https://via.placeholder.com/600/771796',
        thumbnailUrl: 'https://via.placeholder.com/150/771796',
      },
      {
        albumId: 1,
        id: 3,
        title: 'officia porro iure quia iusto qui ipsa ut modi',
        url: 'https://via.placeholder.com/600/24f355',
        thumbnailUrl: 'https://via.placeholder.com/150/24f355',
      },
      {
        albumId: 1,
        id: 4,
        title: 'culpa odio esse rerum omnis laboriosam voluptate repudiandae',
        url: 'https://via.placeholder.com/600/d32776',
        thumbnailUrl: 'https://via.placeholder.com/150/d32776',
      },
      {
        albumId: 1,
        id: 5,
        title: 'natus nisi omnis corporis facere molestiae rerum in',
        url: 'https://via.placeholder.com/600/f66b97',
        thumbnailUrl: 'https://via.placeholder.com/150/f66b97',
      },
      {
        albumId: 1,
        id: 6,
        title: 'accusamus ea aliquid et amet sequi nemo',
        url: 'https://via.placeholder.com/600/56a8c2',
        thumbnailUrl: 'https://via.placeholder.com/150/56a8c2',
      },
      {
        albumId: 1,
        id: 7,
        title:
          'officia delectus consequatur vero aut veniam explicabo molestias',
        url: 'https://via.placeholder.com/600/b0f7cc',
        thumbnailUrl: 'https://via.placeholder.com/150/b0f7cc',
      },
      {
        albumId: 1,
        id: 8,
        title: 'aut porro officiis laborum odit ea laudantium corporis',
        url: 'https://via.placeholder.com/600/54176f',
        thumbnailUrl: 'https://via.placeholder.com/150/54176f',
      },
      {
        albumId: 1,
        id: 9,
        title: 'qui eius qui autem sed',
        url: 'https://via.placeholder.com/600/51aa97',
        thumbnailUrl: 'https://via.placeholder.com/150/51aa97',
      },
      {
        albumId: 1,
        id: 10,
        title: 'beatae et provident et ut vel',
        url: 'https://via.placeholder.com/600/810b14',
        thumbnailUrl: 'https://via.placeholder.com/150/810b14',
      },
      {
        albumId: 1,
        id: 11,
        title: 'nihil at amet non hic quia qui',
        url: 'https://via.placeholder.com/600/1ee8a4',
        thumbnailUrl: 'https://via.placeholder.com/150/1ee8a4',
      },
      {
        albumId: 1,
        id: 12,
        title:
          'mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores',
        url: 'https://via.placeholder.com/600/66b7d2',
        thumbnailUrl: 'https://via.placeholder.com/150/66b7d2',
      },
      {
        albumId: 1,
        id: 13,
        title: 'repudiandae iusto deleniti rerum',
        url: 'https://via.placeholder.com/600/197d29',
        thumbnailUrl: 'https://via.placeholder.com/150/197d29',
      },
      {
        albumId: 1,
        id: 14,
        title: 'est necessitatibus architecto ut laborum',
        url: 'https://via.placeholder.com/600/61a65',
        thumbnailUrl: 'https://via.placeholder.com/150/61a65',
      },
      {
        albumId: 1,
        id: 15,
        title: 'harum dicta similique quis dolore earum ex qui',
        url: 'https://via.placeholder.com/600/f9cee5',
        thumbnailUrl: 'https://via.placeholder.com/150/f9cee5',
      },
      {
        albumId: 1,
        id: 16,
        title:
          'iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt',
        url: 'https://via.placeholder.com/600/fdf73e',
        thumbnailUrl: 'https://via.placeholder.com/150/fdf73e',
      },
      {
        albumId: 1,
        id: 17,
        title: 'natus doloribus necessitatibus ipsa',
        url: 'https://via.placeholder.com/600/9c184f',
        thumbnailUrl: 'https://via.placeholder.com/150/9c184f',
      },
      {
        albumId: 1,
        id: 18,
        title: 'laboriosam odit nam necessitatibus et illum dolores reiciendis',
        url: 'https://via.placeholder.com/600/1fe46f',
        thumbnailUrl: 'https://via.placeholder.com/150/1fe46f',
      },
      {
        albumId: 1,
        id: 19,
        title: 'perferendis nesciunt eveniet et optio a',
        url: 'https://via.placeholder.com/600/56acb2',
        thumbnailUrl: 'https://via.placeholder.com/150/56acb2',
      },
      {
        albumId: 1,
        id: 20,
        title:
          'assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error',
        url: 'https://via.placeholder.com/600/8985dc',
        thumbnailUrl: 'https://via.placeholder.com/150/8985dc',
      },
      {
        albumId: 1,
        id: 21,
        title: 'ad et natus qui',
        url: 'https://via.placeholder.com/600/5e12c6',
        thumbnailUrl: 'https://via.placeholder.com/150/5e12c6',
      },
      {
        albumId: 1,
        id: 22,
        title: 'et ea illo et sit voluptas animi blanditiis porro',
        url: 'https://via.placeholder.com/600/45601a',
        thumbnailUrl: 'https://via.placeholder.com/150/45601a',
      },
      {
        albumId: 1,
        id: 23,
        title: 'harum velit vero totam',
        url: 'https://via.placeholder.com/600/e924e6',
        thumbnailUrl: 'https://via.placeholder.com/150/e924e6',
      },
      {
        albumId: 1,
        id: 24,
        title: 'beatae officiis ut aut',
        url: 'https://via.placeholder.com/600/8f209a',
        thumbnailUrl: 'https://via.placeholder.com/150/8f209a',
      },
      {
        albumId: 1,
        id: 25,
        title: 'facere non quis fuga fugit vitae',
        url: 'https://via.placeholder.com/600/5e3a73',
        thumbnailUrl: 'https://via.placeholder.com/150/5e3a73',
      },
      {
        albumId: 1,
        id: 26,
        title: 'asperiores nobis voluptate qui',
        url: 'https://via.placeholder.com/600/474645',
        thumbnailUrl: 'https://via.placeholder.com/150/474645',
      },
      {
        albumId: 1,
        id: 27,
        title: 'sit asperiores est quos quis nisi veniam error',
        url: 'https://via.placeholder.com/600/c984bf',
        thumbnailUrl: 'https://via.placeholder.com/150/c984bf',
      },
      {
        albumId: 1,
        id: 28,
        title:
          'non neque eligendi molestiae repudiandae illum voluptatem qui aut',
        url: 'https://via.placeholder.com/600/392537',
        thumbnailUrl: 'https://via.placeholder.com/150/392537',
      },
      {
        albumId: 1,
        id: 29,
        title: 'aut ipsam quos ab placeat omnis',
        url: 'https://via.placeholder.com/600/602b9e',
        thumbnailUrl: 'https://via.placeholder.com/150/602b9e',
      },
      {
        albumId: 1,
        id: 30,
        title: 'odio enim voluptatem quidem aut nihil illum',
        url: 'https://via.placeholder.com/600/372c93',
        thumbnailUrl: 'https://via.placeholder.com/150/372c93',
      },
      {
        albumId: 1,
        id: 31,
        title: 'voluptate voluptates sequi',
        url: 'https://via.placeholder.com/600/a7c272',
        thumbnailUrl: 'https://via.placeholder.com/150/a7c272',
      },
      {
        albumId: 1,
        id: 32,
        title: 'ad enim dignissimos voluptatem similique',
        url: 'https://via.placeholder.com/600/c70a4d',
        thumbnailUrl: 'https://via.placeholder.com/150/c70a4d',
      },
      {
        albumId: 1,
        id: 33,
        title: 'culpa ipsam nobis qui fuga magni et mollitia',
        url: 'https://via.placeholder.com/600/501fe1',
        thumbnailUrl: 'https://via.placeholder.com/150/501fe1',
      },
      {
        albumId: 1,
        id: 34,
        title: 'vitae est facere quia itaque adipisci perferendis id maiores',
        url: 'https://via.placeholder.com/600/35185e',
        thumbnailUrl: 'https://via.placeholder.com/150/35185e',
      },
      {
        albumId: 1,
        id: 35,
        title: 'tenetur minus voluptatum et',
        url: 'https://via.placeholder.com/600/c96cad',
        thumbnailUrl: 'https://via.placeholder.com/150/c96cad',
      },
      {
        albumId: 1,
        id: 36,
        title: 'expedita rerum eaque',
        url: 'https://via.placeholder.com/600/4d564d',
        thumbnailUrl: 'https://via.placeholder.com/150/4d564d',
      },
      {
        albumId: 1,
        id: 37,
        title: 'totam voluptas iusto deserunt dolores',
        url: 'https://via.placeholder.com/600/ea51da',
        thumbnailUrl: 'https://via.placeholder.com/150/ea51da',
      },
      {
        albumId: 1,
        id: 38,
        title: 'natus magnam iure rerum pariatur molestias dolore nisi',
        url: 'https://via.placeholder.com/600/4f5b8d',
        thumbnailUrl: 'https://via.placeholder.com/150/4f5b8d',
      },
      {
        albumId: 1,
        id: 39,
        title: 'molestiae nam ullam et rerum doloribus',
        url: 'https://via.placeholder.com/600/1e71a2',
        thumbnailUrl: 'https://via.placeholder.com/150/1e71a2',
      },
      {
        albumId: 1,
        id: 40,
        title:
          'est quas voluptates dignissimos sint praesentium nisi recusandae',
        url: 'https://via.placeholder.com/600/3a0b95',
        thumbnailUrl: 'https://via.placeholder.com/150/3a0b95',
      },
      {
        albumId: 1,
        id: 41,
        title: 'in voluptatem doloremque cum atque architecto deleniti',
        url: 'https://via.placeholder.com/600/659403',
        thumbnailUrl: 'https://via.placeholder.com/150/659403',
      },
      {
        albumId: 1,
        id: 42,
        title: 'voluptatibus a autem molestias voluptas architecto culpa',
        url: 'https://via.placeholder.com/600/ca50ac',
        thumbnailUrl: 'https://via.placeholder.com/150/ca50ac',
      },
      {
        albumId: 1,
        id: 43,
        title: 'eius hic autem ad beatae voluptas',
        url: 'https://via.placeholder.com/600/6ad437',
        thumbnailUrl: 'https://via.placeholder.com/150/6ad437',
      },
      {
        albumId: 1,
        id: 44,
        title: 'neque eum provident et inventore sed ipsam dignissimos quo',
        url: 'https://via.placeholder.com/600/29fe9f',
        thumbnailUrl: 'https://via.placeholder.com/150/29fe9f',
      },
      {
        albumId: 1,
        id: 45,
        title: 'praesentium fugit quis aut voluptatum commodi dolore corrupti',
        url: 'https://via.placeholder.com/600/c4084a',
        thumbnailUrl: 'https://via.placeholder.com/150/c4084a',
      },
      {
        albumId: 1,
        id: 46,
        title: 'quidem maiores in quia fugit dolore explicabo occaecati',
        url: 'https://via.placeholder.com/600/e9b68',
        thumbnailUrl: 'https://via.placeholder.com/150/e9b68',
      },
      {
        albumId: 1,
        id: 47,
        title: 'et soluta est',
        url: 'https://via.placeholder.com/600/b4412f',
        thumbnailUrl: 'https://via.placeholder.com/150/b4412f',
      },
      {
        albumId: 1,
        id: 48,
        title: 'ut esse id',
        url: 'https://via.placeholder.com/600/68e0a8',
        thumbnailUrl: 'https://via.placeholder.com/150/68e0a8',
      },
      {
        albumId: 1,
        id: 49,
        title: 'quasi quae est modi quis quam in impedit',
        url: 'https://via.placeholder.com/600/2cd88b',
        thumbnailUrl: 'https://via.placeholder.com/150/2cd88b',
      },
      {
        albumId: 1,
        id: 50,
        title: 'et inventore quae ut tempore eius voluptatum',
        url: 'https://via.placeholder.com/600/9e59da',
        thumbnailUrl: 'https://via.placeholder.com/150/9e59da',
      },
    ],
  },
  {
    id: 'category_4',
    title: 'Category 4',
    data: [
      {
        albumId: 1,
        id: 1,
        title: 'accusamus beatae ad facilis cum similique qui sunt',
        url: 'https://via.placeholder.com/150/92c952',
        thumbnailUrl: 'https://via.placeholder.com/150/92c952',
      },
      {
        albumId: 1,
        id: 2,
        title: 'reprehenderit est deserunt velit ipsam',
        url: 'https://via.placeholder.com/150/771796',
        thumbnailUrl: 'https://via.placeholder.com/150/771796',
      },
      {
        albumId: 1,
        id: 3,
        title: 'officia porro iure quia iusto qui ipsa ut modi',
        url: 'https://via.placeholder.com/150/24f355',
        thumbnailUrl: 'https://via.placeholder.com/150/24f355',
      },
      {
        albumId: 1,
        id: 4,
        title: 'culpa odio esse rerum omnis laboriosam voluptate repudiandae',
        url: 'https://via.placeholder.com/150/d32776',
        thumbnailUrl: 'https://via.placeholder.com/150/d32776',
      },
      {
        albumId: 1,
        id: 5,
        title: 'natus nisi omnis corporis facere molestiae rerum in',
        url: 'https://via.placeholder.com/150/f66b97',
        thumbnailUrl: 'https://via.placeholder.com/150/f66b97',
      },
      {
        albumId: 1,
        id: 6,
        title: 'accusamus ea aliquid et amet sequi nemo',
        url: 'https://via.placeholder.com/150/56a8c2',
        thumbnailUrl: 'https://via.placeholder.com/150/56a8c2',
      },
      {
        albumId: 1,
        id: 7,
        title:
          'officia delectus consequatur vero aut veniam explicabo molestias',
        url: 'https://via.placeholder.com/150/b0f7cc',
        thumbnailUrl: 'https://via.placeholder.com/150/b0f7cc',
      },
      {
        albumId: 1,
        id: 8,
        title: 'aut porro officiis laborum odit ea laudantium corporis',
        url: 'https://via.placeholder.com/150/54176f',
        thumbnailUrl: 'https://via.placeholder.com/150/54176f',
      },
      {
        albumId: 1,
        id: 9,
        title: 'qui eius qui autem sed',
        url: 'https://via.placeholder.com/150/51aa97',
        thumbnailUrl: 'https://via.placeholder.com/150/51aa97',
      },
      {
        albumId: 1,
        id: 10,
        title: 'beatae et provident et ut vel',
        url: 'https://via.placeholder.com/150/810b14',
        thumbnailUrl: 'https://via.placeholder.com/150/810b14',
      },
      {
        albumId: 1,
        id: 11,
        title: 'nihil at amet non hic quia qui',
        url: 'https://via.placeholder.com/150/1ee8a4',
        thumbnailUrl: 'https://via.placeholder.com/150/1ee8a4',
      },
      {
        albumId: 1,
        id: 12,
        title:
          'mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores',
        url: 'https://via.placeholder.com/150/66b7d2',
        thumbnailUrl: 'https://via.placeholder.com/150/66b7d2',
      },
      {
        albumId: 1,
        id: 13,
        title: 'repudiandae iusto deleniti rerum',
        url: 'https://via.placeholder.com/150/197d29',
        thumbnailUrl: 'https://via.placeholder.com/150/197d29',
      },
      {
        albumId: 1,
        id: 14,
        title: 'est necessitatibus architecto ut laborum',
        url: 'https://via.placeholder.com/150/61a65',
        thumbnailUrl: 'https://via.placeholder.com/150/61a65',
      },
      {
        albumId: 1,
        id: 15,
        title: 'harum dicta similique quis dolore earum ex qui',
        url: 'https://via.placeholder.com/150/f9cee5',
        thumbnailUrl: 'https://via.placeholder.com/150/f9cee5',
      },
      {
        albumId: 1,
        id: 16,
        title:
          'iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt',
        url: 'https://via.placeholder.com/150/fdf73e',
        thumbnailUrl: 'https://via.placeholder.com/150/fdf73e',
      },
      {
        albumId: 1,
        id: 17,
        title: 'natus doloribus necessitatibus ipsa',
        url: 'https://via.placeholder.com/150/9c184f',
        thumbnailUrl: 'https://via.placeholder.com/150/9c184f',
      },
      {
        albumId: 1,
        id: 18,
        title: 'laboriosam odit nam necessitatibus et illum dolores reiciendis',
        url: 'https://via.placeholder.com/150/1fe46f',
        thumbnailUrl: 'https://via.placeholder.com/150/1fe46f',
      },
      {
        albumId: 1,
        id: 19,
        title: 'perferendis nesciunt eveniet et optio a',
        url: 'https://via.placeholder.com/150/56acb2',
        thumbnailUrl: 'https://via.placeholder.com/150/56acb2',
      },
      {
        albumId: 1,
        id: 20,
        title:
          'assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error',
        url: 'https://via.placeholder.com/150/8985dc',
        thumbnailUrl: 'https://via.placeholder.com/150/8985dc',
      },
      {
        albumId: 1,
        id: 21,
        title: 'ad et natus qui',
        url: 'https://via.placeholder.com/150/5e12c6',
        thumbnailUrl: 'https://via.placeholder.com/150/5e12c6',
      },
      {
        albumId: 1,
        id: 22,
        title: 'et ea illo et sit voluptas animi blanditiis porro',
        url: 'https://via.placeholder.com/150/45601a',
        thumbnailUrl: 'https://via.placeholder.com/150/45601a',
      },
      {
        albumId: 1,
        id: 23,
        title: 'harum velit vero totam',
        url: 'https://via.placeholder.com/150/e924e6',
        thumbnailUrl: 'https://via.placeholder.com/150/e924e6',
      },
      {
        albumId: 1,
        id: 24,
        title: 'beatae officiis ut aut',
        url: 'https://via.placeholder.com/150/8f209a',
        thumbnailUrl: 'https://via.placeholder.com/150/8f209a',
      },
      {
        albumId: 1,
        id: 25,
        title: 'facere non quis fuga fugit vitae',
        url: 'https://via.placeholder.com/150/5e3a73',
        thumbnailUrl: 'https://via.placeholder.com/150/5e3a73',
      },
      {
        albumId: 1,
        id: 26,
        title: 'asperiores nobis voluptate qui',
        url: 'https://via.placeholder.com/150/474645',
        thumbnailUrl: 'https://via.placeholder.com/150/474645',
      },
      {
        albumId: 1,
        id: 27,
        title: 'sit asperiores est quos quis nisi veniam error',
        url: 'https://via.placeholder.com/150/c984bf',
        thumbnailUrl: 'https://via.placeholder.com/150/c984bf',
      },
      {
        albumId: 1,
        id: 28,
        title:
          'non neque eligendi molestiae repudiandae illum voluptatem qui aut',
        url: 'https://via.placeholder.com/150/392537',
        thumbnailUrl: 'https://via.placeholder.com/150/392537',
      },
      {
        albumId: 1,
        id: 29,
        title: 'aut ipsam quos ab placeat omnis',
        url: 'https://via.placeholder.com/150/602b9e',
        thumbnailUrl: 'https://via.placeholder.com/150/602b9e',
      },
      {
        albumId: 1,
        id: 30,
        title: 'odio enim voluptatem quidem aut nihil illum',
        url: 'https://via.placeholder.com/150/372c93',
        thumbnailUrl: 'https://via.placeholder.com/150/372c93',
      },
      {
        albumId: 1,
        id: 31,
        title: 'voluptate voluptates sequi',
        url: 'https://via.placeholder.com/150/a7c272',
        thumbnailUrl: 'https://via.placeholder.com/150/a7c272',
      },
      {
        albumId: 1,
        id: 32,
        title: 'ad enim dignissimos voluptatem similique',
        url: 'https://via.placeholder.com/150/c70a4d',
        thumbnailUrl: 'https://via.placeholder.com/150/c70a4d',
      },
      {
        albumId: 1,
        id: 33,
        title: 'culpa ipsam nobis qui fuga magni et mollitia',
        url: 'https://via.placeholder.com/150/501fe1',
        thumbnailUrl: 'https://via.placeholder.com/150/501fe1',
      },
      {
        albumId: 1,
        id: 34,
        title: 'vitae est facere quia itaque adipisci perferendis id maiores',
        url: 'https://via.placeholder.com/150/35185e',
        thumbnailUrl: 'https://via.placeholder.com/150/35185e',
      },
      {
        albumId: 1,
        id: 35,
        title: 'tenetur minus voluptatum et',
        url: 'https://via.placeholder.com/150/c96cad',
        thumbnailUrl: 'https://via.placeholder.com/150/c96cad',
      },
      {
        albumId: 1,
        id: 36,
        title: 'expedita rerum eaque',
        url: 'https://via.placeholder.com/150/4d564d',
        thumbnailUrl: 'https://via.placeholder.com/150/4d564d',
      },
      {
        albumId: 1,
        id: 37,
        title: 'totam voluptas iusto deserunt dolores',
        url: 'https://via.placeholder.com/150/ea51da',
        thumbnailUrl: 'https://via.placeholder.com/150/ea51da',
      },
      {
        albumId: 1,
        id: 38,
        title: 'natus magnam iure rerum pariatur molestias dolore nisi',
        url: 'https://via.placeholder.com/150/4f5b8d',
        thumbnailUrl: 'https://via.placeholder.com/150/4f5b8d',
      },
      {
        albumId: 1,
        id: 39,
        title: 'molestiae nam ullam et rerum doloribus',
        url: 'https://via.placeholder.com/150/1e71a2',
        thumbnailUrl: 'https://via.placeholder.com/150/1e71a2',
      },
      {
        albumId: 1,
        id: 40,
        title:
          'est quas voluptates dignissimos sint praesentium nisi recusandae',
        url: 'https://via.placeholder.com/150/3a0b95',
        thumbnailUrl: 'https://via.placeholder.com/150/3a0b95',
      },
      {
        albumId: 1,
        id: 41,
        title: 'in voluptatem doloremque cum atque architecto deleniti',
        url: 'https://via.placeholder.com/150/659403',
        thumbnailUrl: 'https://via.placeholder.com/150/659403',
      },
      {
        albumId: 1,
        id: 42,
        title: 'voluptatibus a autem molestias voluptas architecto culpa',
        url: 'https://via.placeholder.com/150/ca50ac',
        thumbnailUrl: 'https://via.placeholder.com/150/ca50ac',
      },
      {
        albumId: 1,
        id: 43,
        title: 'eius hic autem ad beatae voluptas',
        url: 'https://via.placeholder.com/150/6ad437',
        thumbnailUrl: 'https://via.placeholder.com/150/6ad437',
      },
      {
        albumId: 1,
        id: 44,
        title: 'neque eum provident et inventore sed ipsam dignissimos quo',
        url: 'https://via.placeholder.com/150/29fe9f',
        thumbnailUrl: 'https://via.placeholder.com/150/29fe9f',
      },
      {
        albumId: 1,
        id: 45,
        title: 'praesentium fugit quis aut voluptatum commodi dolore corrupti',
        url: 'https://via.placeholder.com/150/c4084a',
        thumbnailUrl: 'https://via.placeholder.com/150/c4084a',
      },
      {
        albumId: 1,
        id: 46,
        title: 'quidem maiores in quia fugit dolore explicabo occaecati',
        url: 'https://via.placeholder.com/150/e9b68',
        thumbnailUrl: 'https://via.placeholder.com/150/e9b68',
      },
      {
        albumId: 1,
        id: 47,
        title: 'et soluta est',
        url: 'https://via.placeholder.com/150/b4412f',
        thumbnailUrl: 'https://via.placeholder.com/150/b4412f',
      },
      {
        albumId: 1,
        id: 48,
        title: 'ut esse id',
        url: 'https://via.placeholder.com/150/68e0a8',
        thumbnailUrl: 'https://via.placeholder.com/150/68e0a8',
      },
      {
        albumId: 1,
        id: 49,
        title: 'quasi quae est modi quis quam in impedit',
        url: 'https://via.placeholder.com/150/2cd88b',
        thumbnailUrl: 'https://via.placeholder.com/150/2cd88b',
      },
      {
        albumId: 1,
        id: 50,
        title: 'et inventore quae ut tempore eius voluptatum',
        url: 'https://via.placeholder.com/150/9e59da',
        thumbnailUrl: 'https://via.placeholder.com/150/9e59da',
      },
    ],
  },
  {
    id: 'category_5',
    title: 'Category 5',
    data: [
      {name: 'Bulgaria', code: 'BG'},
      {name: 'Burkina Faso', code: 'BF'},
      {name: 'Burundi', code: 'BI'},
      {name: 'Cambodia', code: 'KH'},
      {name: 'Cameroon', code: 'CM'},
      {name: 'Canada', code: 'CA'},
      {name: 'Cape Verde', code: 'CV'},
      {name: 'Cayman Islands', code: 'KY'},
      {name: 'Central African Republic', code: 'CF'},
      {name: 'Chad', code: 'TD'},
      {name: 'Chile', code: 'CL'},
      {name: 'China', code: 'CN'},
      {name: 'Christmas Island', code: 'CX'},
      {name: 'Cocos (Keeling) Islands', code: 'CC'},
      {name: 'Colombia', code: 'CO'},
      {name: 'Comoros', code: 'KM'},
      {name: 'Congo', code: 'CG'},
      {name: 'Congo, The Democratic Republic of the', code: 'CD'},
      {name: 'Cook Islands', code: 'CK'},
      {name: 'Costa Rica', code: 'CR'},
      {name: "Cote D'Ivoire", code: 'CI'},
      {name: 'Croatia', code: 'HR'},
      {name: 'Cuba', code: 'CU'},
      {name: 'Cyprus', code: 'CY'},
      {name: 'Czech Republic', code: 'CZ'},
      {name: 'Denmark', code: 'DK'},
      {name: 'Djibouti', code: 'DJ'},
    ],
  },
  {
    id: 'countries_list',
    title: 'Countries List',
    data: [
      {name: 'Afghanistan', code: 'AF'},
      {name: 'Åland Islands', code: 'AX'},
      {name: 'Albania', code: 'AL'},
      {name: 'Algeria', code: 'DZ'},
      {name: 'American Samoa', code: 'AS'},
      {name: 'AndorrA', code: 'AD'},
      {name: 'Angola', code: 'AO'},
      {name: 'Anguilla', code: 'AI'},
      {name: 'Antarctica', code: 'AQ'},
      {name: 'Antigua and Barbuda', code: 'AG'},
      {name: 'Argentina', code: 'AR'},
      {name: 'Armenia', code: 'AM'},
      {name: 'Aruba', code: 'AW'},
      {name: 'Australia', code: 'AU'},
      {name: 'Austria', code: 'AT'},
      {name: 'Azerbaijan', code: 'AZ'},
      {name: 'Bahamas', code: 'BS'},
      {name: 'Bahrain', code: 'BH'},
      {name: 'Bangladesh', code: 'BD'},
      {name: 'Barbados', code: 'BB'},
      {name: 'Belarus', code: 'BY'},
      {name: 'Belgium', code: 'BE'},
      {name: 'Belize', code: 'BZ'},
      {name: 'Benin', code: 'BJ'},
      {name: 'Bermuda', code: 'BM'},
      {name: 'Bhutan', code: 'BT'},
      {name: 'Bolivia', code: 'BO'},
      {name: 'Bosnia and Herzegovina', code: 'BA'},
      {name: 'Botswana', code: 'BW'},
      {name: 'Bouvet Island', code: 'BV'},
      {name: 'Brazil', code: 'BR'},
      {name: 'British Indian Ocean Territory', code: 'IO'},
      {name: 'Brunei Darussalam', code: 'BN'},
      {name: 'Bulgaria', code: 'BG'},
      {name: 'Burkina Faso', code: 'BF'},
      {name: 'Burundi', code: 'BI'},
      {name: 'Cambodia', code: 'KH'},
      {name: 'Cameroon', code: 'CM'},
      {name: 'Canada', code: 'CA'},
      {name: 'Cape Verde', code: 'CV'},
      {name: 'Cayman Islands', code: 'KY'},
      {name: 'Central African Republic', code: 'CF'},
      {name: 'Chad', code: 'TD'},
      {name: 'Chile', code: 'CL'},
      {name: 'China', code: 'CN'},
      {name: 'Christmas Island', code: 'CX'},
      {name: 'Cocos (Keeling) Islands', code: 'CC'},
      {name: 'Colombia', code: 'CO'},
      {name: 'Comoros', code: 'KM'},
      {name: 'Congo', code: 'CG'},
      {name: 'Congo, The Democratic Republic of the', code: 'CD'},
      {name: 'Cook Islands', code: 'CK'},
      {name: 'Costa Rica', code: 'CR'},
      {name: "Cote D'Ivoire", code: 'CI'},
      {name: 'Croatia', code: 'HR'},
      {name: 'Cuba', code: 'CU'},
      {name: 'Cyprus', code: 'CY'},
      {name: 'Czech Republic', code: 'CZ'},
      {name: 'Denmark', code: 'DK'},
      {name: 'Djibouti', code: 'DJ'},
      {name: 'Dominica', code: 'DM'},
      {name: 'Dominican Republic', code: 'DO'},
      {name: 'Ecuador', code: 'EC'},
      {name: 'Egypt', code: 'EG'},
      {name: 'El Salvador', code: 'SV'},
      {name: 'Equatorial Guinea', code: 'GQ'},
      {name: 'Eritrea', code: 'ER'},
      {name: 'Estonia', code: 'EE'},
      {name: 'Ethiopia', code: 'ET'},
      {name: 'Falkland Islands (Malvinas)', code: 'FK'},
      {name: 'Faroe Islands', code: 'FO'},
      {name: 'Fiji', code: 'FJ'},
      {name: 'Finland', code: 'FI'},
      {name: 'France', code: 'FR'},
      {name: 'French Guiana', code: 'GF'},
      {name: 'French Polynesia', code: 'PF'},
      {name: 'French Southern Territories', code: 'TF'},
      {name: 'Gabon', code: 'GA'},
      {name: 'Gambia', code: 'GM'},
      {name: 'Georgia', code: 'GE'},
      {name: 'Germany', code: 'DE'},
      {name: 'Ghana', code: 'GH'},
      {name: 'Gibraltar', code: 'GI'},
      {name: 'Greece', code: 'GR'},
      {name: 'Greenland', code: 'GL'},
      {name: 'Grenada', code: 'GD'},
      {name: 'Guadeloupe', code: 'GP'},
      {name: 'Guam', code: 'GU'},
      {name: 'Guatemala', code: 'GT'},
      {name: 'Guernsey', code: 'GG'},
      {name: 'Guinea', code: 'GN'},
      {name: 'Guinea-Bissau', code: 'GW'},
      {name: 'Guyana', code: 'GY'},
      {name: 'Haiti', code: 'HT'},
      {name: 'Heard Island and Mcdonald Islands', code: 'HM'},
      {name: 'Holy See (Vatican City State)', code: 'VA'},
      {name: 'Honduras', code: 'HN'},
      {name: 'Hong Kong', code: 'HK'},
      {name: 'Hungary', code: 'HU'},
      {name: 'Iceland', code: 'IS'},
      {name: 'India', code: 'IN'},
      {name: 'Indonesia', code: 'ID'},
      {name: 'Iran, Islamic Republic Of', code: 'IR'},
      {name: 'Iraq', code: 'IQ'},
      {name: 'Ireland', code: 'IE'},
      {name: 'Isle of Man', code: 'IM'},
      {name: 'Israel', code: 'IL'},
      {name: 'Italy', code: 'IT'},
      {name: 'Jamaica', code: 'JM'},
      {name: 'Japan', code: 'JP'},
      {name: 'Jersey', code: 'JE'},
      {name: 'Jordan', code: 'JO'},
      {name: 'Kazakhstan', code: 'KZ'},
      {name: 'Kenya', code: 'KE'},
      {name: 'Kiribati', code: 'KI'},
      {name: "Korea, Democratic People'S Republic of", code: 'KP'},
      {name: 'Korea, Republic of', code: 'KR'},
      {name: 'Kuwait', code: 'KW'},
      {name: 'Kyrgyzstan', code: 'KG'},
      {name: "Lao People'S Democratic Republic", code: 'LA'},
      {name: 'Latvia', code: 'LV'},
      {name: 'Lebanon', code: 'LB'},
      {name: 'Lesotho', code: 'LS'},
      {name: 'Liberia', code: 'LR'},
      {name: 'Libyan Arab Jamahiriya', code: 'LY'},
      {name: 'Liechtenstein', code: 'LI'},
      {name: 'Lithuania', code: 'LT'},
      {name: 'Luxembourg', code: 'LU'},
      {name: 'Macao', code: 'MO'},
      {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
      {name: 'Madagascar', code: 'MG'},
      {name: 'Malawi', code: 'MW'},
      {name: 'Malaysia', code: 'MY'},
      {name: 'Maldives', code: 'MV'},
      {name: 'Mali', code: 'ML'},
      {name: 'Malta', code: 'MT'},
      {name: 'Marshall Islands', code: 'MH'},
      {name: 'Martinique', code: 'MQ'},
      {name: 'Mauritania', code: 'MR'},
      {name: 'Mauritius', code: 'MU'},
      {name: 'Mayotte', code: 'YT'},
      {name: 'Mexico', code: 'MX'},
      {name: 'Micronesia, Federated States of', code: 'FM'},
      {name: 'Moldova, Republic of', code: 'MD'},
      {name: 'Monaco', code: 'MC'},
      {name: 'Mongolia', code: 'MN'},
      {name: 'Montserrat', code: 'MS'},
      {name: 'Morocco', code: 'MA'},
      {name: 'Mozambique', code: 'MZ'},
      {name: 'Myanmar', code: 'MM'},
      {name: 'Namibia', code: 'NA'},
      {name: 'Nauru', code: 'NR'},
      {name: 'Nepal', code: 'NP'},
      {name: 'Netherlands', code: 'NL'},
      {name: 'Netherlands Antilles', code: 'AN'},
      {name: 'New Caledonia', code: 'NC'},
      {name: 'New Zealand', code: 'NZ'},
      {name: 'Nicaragua', code: 'NI'},
      {name: 'Niger', code: 'NE'},
      {name: 'Nigeria', code: 'NG'},
      {name: 'Niue', code: 'NU'},
      {name: 'Norfolk Island', code: 'NF'},
      {name: 'Northern Mariana Islands', code: 'MP'},
      {name: 'Norway', code: 'NO'},
      {name: 'Oman', code: 'OM'},
      {name: 'Pakistan', code: 'PK'},
      {name: 'Palau', code: 'PW'},
      {name: 'Palestinian Territory, Occupied', code: 'PS'},
      {name: 'Panama', code: 'PA'},
      {name: 'Papua New Guinea', code: 'PG'},
      {name: 'Paraguay', code: 'PY'},
      {name: 'Peru', code: 'PE'},
      {name: 'Philippines', code: 'PH'},
      {name: 'Pitcairn', code: 'PN'},
      {name: 'Poland', code: 'PL'},
      {name: 'Portugal', code: 'PT'},
      {name: 'Puerto Rico', code: 'PR'},
      {name: 'Qatar', code: 'QA'},
      {name: 'Reunion', code: 'RE'},
      {name: 'Romania', code: 'RO'},
      {name: 'Russian Federation', code: 'RU'},
      {name: 'RWANDA', code: 'RW'},
      {name: 'Saint Helena', code: 'SH'},
      {name: 'Saint Kitts and Nevis', code: 'KN'},
      {name: 'Saint Lucia', code: 'LC'},
      {name: 'Saint Pierre and Miquelon', code: 'PM'},
      {name: 'Saint Vincent and the Grenadines', code: 'VC'},
      {name: 'Samoa', code: 'WS'},
      {name: 'San Marino', code: 'SM'},
      {name: 'Sao Tome and Principe', code: 'ST'},
      {name: 'Saudi Arabia', code: 'SA'},
      {name: 'Senegal', code: 'SN'},
      {name: 'Serbia and Montenegro', code: 'CS'},
      {name: 'Seychelles', code: 'SC'},
      {name: 'Sierra Leone', code: 'SL'},
      {name: 'Singapore', code: 'SG'},
      {name: 'Slovakia', code: 'SK'},
      {name: 'Slovenia', code: 'SI'},
      {name: 'Solomon Islands', code: 'SB'},
      {name: 'Somalia', code: 'SO'},
      {name: 'South Africa', code: 'ZA'},
      {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
      {name: 'Spain', code: 'ES'},
      {name: 'Sri Lanka', code: 'LK'},
      {name: 'Sudan', code: 'SD'},
      {name: 'Suriname', code: 'SR'},
      {name: 'Svalbard and Jan Mayen', code: 'SJ'},
      {name: 'Swaziland', code: 'SZ'},
      {name: 'Sweden', code: 'SE'},
      {name: 'Switzerland', code: 'CH'},
      {name: 'Syrian Arab Republic', code: 'SY'},
      {name: 'Taiwan, Province of China', code: 'TW'},
      {name: 'Tajikistan', code: 'TJ'},
      {name: 'Tanzania, United Republic of', code: 'TZ'},
      {name: 'Thailand', code: 'TH'},
      {name: 'Timor-Leste', code: 'TL'},
      {name: 'Togo', code: 'TG'},
      {name: 'Tokelau', code: 'TK'},
      {name: 'Tonga', code: 'TO'},
      {name: 'Trinidad and Tobago', code: 'TT'},
      {name: 'Tunisia', code: 'TN'},
      {name: 'Turkey', code: 'TR'},
      {name: 'Turkmenistan', code: 'TM'},
      {name: 'Turks and Caicos Islands', code: 'TC'},
      {name: 'Tuvalu', code: 'TV'},
      {name: 'Uganda', code: 'UG'},
      {name: 'Ukraine', code: 'UA'},
      {name: 'United Arab Emirates', code: 'AE'},
      {name: 'United Kingdom', code: 'GB'},
      {name: 'United States', code: 'US'},
      {name: 'United States Minor Outlying Islands', code: 'UM'},
      {name: 'Uruguay', code: 'UY'},
      {name: 'Uzbekistan', code: 'UZ'},
      {name: 'Vanuatu', code: 'VU'},
      {name: 'Venezuela', code: 'VE'},
      {name: 'Viet Nam', code: 'VN'},
      {name: 'Virgin Islands, British', code: 'VG'},
      {name: 'Virgin Islands, U.S.', code: 'VI'},
      {name: 'Wallis and Futuna', code: 'WF'},
      {name: 'Western Sahara', code: 'EH'},
      {name: 'Yemen', code: 'YE'},
      {name: 'Zambia', code: 'ZM'},
      {name: 'Zimbabwe', code: 'ZW'},
    ],
  },
];
export default data;
